## CMPINF 2100 Week 03
### Introduction to 1D NumPy arrays
NumPy is allowed Python to any kind of Data Analysis.
NumPy is a moduel and we need to import it

In [1]:
import numpy as np

In [2]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


## NumPy 1D Array
the **ndarray** is the horse of NumPy. Let's start with 1D array
### Create 1D arrays

In [4]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [11]:
a_list = list(range(6))

In [12]:
 a = np.arange(6)

In [13]:
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

Similar between array and list - we can slice/index bothe objects

In [14]:
a[:3]

array([0, 1, 2])

### Attributes

In [15]:
len(a_list)

6

a.ndim

In [16]:
a.shape

(6,)

In [17]:
a.size

6

In [18]:
type(a.shape)

tuple

In [21]:
a

array([0, 1, 2, 3, 4, 5])

### Other ways to create arrays
One way to make array is with np.array() runction. This let us CONVERT a LIST or a TUPLE to an array

In [23]:
a1 = np.array([1,2,3,4,5])

In [24]:
%whos

Variable   Type       Data/Info
-------------------------------
a          ndarray    6: 6 elems, type `int64`, 48 bytes
a1         ndarray    5: 5 elems, type `int64`, 40 bytes
a_list     list       n=6
np         module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


In [25]:
a1.ndim

1

In [26]:
a1.shape

(5,)

In [27]:
a1.size

5

In [28]:
a1

array([1, 2, 3, 4, 5])

In [29]:
print(a1)

[1 2 3 4 5]


In [30]:
a2 = np.array((1,2,3,4,5))

In [31]:
a2

array([1, 2, 3, 4, 5])

In [32]:
a2.ndim

1

In [33]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [34]:
np.ones(4)

array([1., 1., 1., 1.])

The 'np.arange()' function has 3 arguments
START, STOP (EXCLUSIVE), and STEP

In [35]:
np.arange(4)

array([0, 1, 2, 3])

In [37]:
np.arange(0, 6, 2)

array([0, 2, 4])

In [38]:
np.arange(0, 100, 20)

array([ 0, 20, 40, 60, 80])

In [40]:
np.arange(0, 100+1, 20) # to include the ending number

array([  0,  20,  40,  60,  80, 100])

the np.linspace() function is very similar to np.arange() BUT..
START, STOP(INCLUSIVE) and number of points

In [41]:
np.linspace(0,6, num=1)

array([0.])

In [42]:
np.linspace(0,6, num=6)

array([0. , 1.2, 2.4, 3.6, 4.8, 6. ])

In [43]:
np.linspace(0,6, num=6+1)

array([0., 1., 2., 3., 4., 5., 6.])

In [44]:
np.arange(-10, 10, 3)

array([-10,  -7,  -4,  -1,   2,   5,   8])

In [45]:
np.linspace(-10, 10, num=17)

array([-10.  ,  -8.75,  -7.5 ,  -6.25,  -5.  ,  -3.75,  -2.5 ,  -1.25,
         0.  ,   1.25,   2.5 ,   3.75,   5.  ,   6.25,   7.5 ,   8.75,
        10.  ])

### Differences
operators may behave differently on NumPy arrays compared to lists

In [46]:
a_list

[0, 1, 2, 3, 4, 5]

In [47]:
a_list == [0,1,2,3,4,5]

True

In [48]:
a

array([0, 1, 2, 3, 4, 5])

In [49]:
a == np.array([0,1,2,3,4,5])

array([ True,  True,  True,  True,  True,  True])

In [54]:
np.array_equal(a, np.array([-10, 1,2,3,4,5]))

False