## CMPINF 2100 Week 03
#### Generating random numbers with NumPy
NumPy greatly streamlines the process of generating many random numbers


In [2]:
import numpy as np

### Random number generators
NumPy has its own family of random number generators. It requires that we initialize or sepcify the GENERATOR object

In [4]:
rg = np.random.default_rng(1234)

In [5]:
%whos

Variable   Type         Data/Info
---------------------------------
np         module       <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
rg         Generator    Generator(PCG64)


Generating random numbers required calling methods
The uniform number between 0 and 1 is created using the rg.random() method

In [6]:
rg.random()

0.9766997666981422

In [7]:
rg.random()

0.3801957350196178

In [8]:
rg = np.random.default_rng(1234)
print( rg.random(), rg.random(), rg.random())

0.9766997666981422 0.3801957350196178 0.9232462337639554


In [9]:
rg = np.random.default_rng(1234)

In [10]:
rg.random(3)

array([0.97669977, 0.38019574, 0.92324623])

In [11]:
rg.random(1001).mean()

0.49614336865861586

In [13]:
rg = np.random.default_rng(1234)

In [14]:
rg.random((4, 2))

array([[0.97669977, 0.38019574],
       [0.92324623, 0.26169242],
       [0.31909706, 0.11809123],
       [0.24176629, 0.31853393]])

In [16]:
rg.random((1000, 10)).shape

(1000, 10)

### Other distributions

In [21]:
help( np.random.random ) 

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [22]:
help( np.random.normal ) 

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    .. note::
        New code should use the `~numpy.random.Generator.normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    loc : float or array_like of floats
     

to generate 7 random numbers from a Gaussian or Bell Curve with mean -100 and standard deviation 5

In [23]:
rg = np.random.default_rng(1234)

In [24]:
rg.normal( -100, 5, 7)

array([-108.01918403,  -99.67950043,  -96.29554352,  -99.23690403,
        -95.68128054,  -85.43450389, -107.3941168 ])

In [25]:
rg.normal( -100, 5, (4, 2))

array([[ -95.27263513, -108.33067729],
       [ -98.28127709, -102.56221855],
       [ -93.38120522, -104.30140097],
       [ -97.402534  , -106.32571859]])