## CMPINF 2100 Week 03
### Introduction to 2D NumPy arrays
we saw how to create, manipulate, modify..what does ID even mean???
### Import NumPy

In [1]:
import numpy as np

### List of lists
Return back to base Python to begin...we have made lists of lists before...
BUt this list of lists will be siple just 2 element,. each element with list of 3 values

In [3]:
[[0,0,0],[1,1,1]]

[[0, 0, 0], [1, 1, 1]]

Do the same thing but more white space and spacing!!!

In [4]:
[[0,0,0],
 [1,1,1]]

[[0, 0, 0], [1, 1, 1]]

In [5]:
my_list_of_lists = [[0,0,0],
 [1,1,1]]

In [6]:
my_list_of_lists

[[0, 0, 0], [1, 1, 1]]

In [7]:
%whos

Variable           Type      Data/Info
--------------------------------------
my_list_of_lists   list      n=2
np                 module    <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


Let's conver the list of list to a NumPy array

In [8]:
my_array = np.array( my_list_of_lists )

In [9]:
type(my_array)

numpy.ndarray

In [10]:
my_array.ndim

2

In [11]:
my_array.shape

(2, 3)

In [12]:
my_array

array([[0, 0, 0],
       [1, 1, 1]])

In [13]:
my_array.shape

(2, 3)

In [14]:
my_array.shape[0]

2

In [15]:
my_array.shape[1]

3

In [16]:
my_array.size

6

In [17]:
my_array.shape[0] * my_array.shape[1]

6

But list of lists does not understand rows and  columns

In [18]:
my_array_b = np.array([[0,0,0],[1,1,1]])

In [19]:
my_array_b.ndim

2

In [20]:
my_array_b

array([[0, 0, 0],
       [1, 1, 1]])

 Creating a 2D array from a list of lists requires each inner list to have the same length!!!

In [22]:
np.array([[0,0,0],
           [1,1,1,1,1,1,1]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

alternatively we can create 2D array from COMBINING 1D array!!!

In [23]:
a = np.zeros(3)

In [24]:
b = np.ones(3)

In [25]:
a.ndim

1

In [26]:
a.shape

(3,)

In [27]:
a

array([0., 0., 0.])

In [28]:
b.ndim

1

In [29]:
b.shape

(3,)

can use np.concatenate() to combine 1D arrays

In [30]:
np.concatenate( [a,b])

array([0., 0., 0., 1., 1., 1.])

In [31]:
np.concatenate( [a, b]).shape

(6,)

Creating a 2D array from 1D array requires changing the syntax to np.concatenate()

In [33]:
np.concatenate([[a],[b]])

array([[0., 0., 0.],
       [1., 1., 1.]])

There are speciality functions that simplify STACKING arrays together!!!
Stacking ON top of each other is known as VERTICAL stacking or VERTICAL combing

In [35]:
np.vstack([a,b])

array([[0., 0., 0.],
       [1., 1., 1.]])

Combing array side by side is known as HORIZONTAL stacking

In [36]:
np.hstack([a,b])

array([0., 0., 0., 1., 1., 1.])

we can combine or stack more than 2 arrays at the same time

In [37]:
c = 2 * np.ones(3)

In [38]:
d = 3 * np.ones(3)

In [39]:
c

array([2., 2., 2.])

In [40]:
d

array([3., 3., 3.])

In [42]:
np.vstack([a,b,c,d])

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])