## CMPINF 2100 Week 03
### Manipulate and SUMMARIZE 1D NumPy arrays
We can modify or manipulate 1D NumPy arrays multiple ways.
* Modify individual values
* Slice/Index to remove elements
* COMBINE arrays together
* Change the ORDER of the values
* SUMMARIZE the values within the array

### Import NumPy

In [1]:
import numpy as np

#### Create an array

In [2]:
a = np.arange(6)

In [3]:
a

array([0, 1, 2, 3, 4, 5])

In [4]:
a.ndim

1

In [5]:
a.shape

(6,)

### Modify values
NumPy arrays are MUTABLE, meaning we can change their values!!!

In [6]:
a

array([0, 1, 2, 3, 4, 5])

### Slice or Index
Slicing or indexing works just as slicing/indexing of base Python lists!

In [7]:
a[0]

0

In [8]:
a[-1]

5

In [10]:
a[:3]

array([0, 1, 2])

In [11]:
a[3:]

array([3, 4, 5])

In [12]:
a

array([0, 1, 2, 3, 4, 5])

In [13]:
a[0] = -101

In [68]:
a

array([-101,    1,    2,    3,    4,    5])

something to keep in mind

In [69]:
a[-1] = 101

In [70]:
b = np.linspace(-5, 5, num=21)

In [71]:
b

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [72]:
b.size

21

In [73]:
a[:3]

array([-101,    1,    2])

# Conditional subset
coniditional subseting filters or slices an array based on a conditional test
what's conditional test?
Is 1 less than 3?

In [74]:
1 < 3

True

Is 5 less than 3

In [75]:
5 < 3

False

In [76]:
a

array([-101,    1,    2,    3,    4,  101])

Check which values are less than 3
We don't need to for loop in NumPy


In [77]:
a < 3

array([ True,  True,  True, False, False, False])

NumPy arrays are intended to be HOMOGENOUS. i.e element should be same data type within array!!!
Let's assign the result of the conditional test to a new object 

In [78]:
a_mask = a < 3

In [79]:
%whos

Variable    Type       Data/Info
--------------------------------
a           ndarray    6: 6 elems, type `int64`, 48 bytes
a_array     ndarray    3: 3 elems, type `int64`, 24 bytes
a_list      list       n=3
a_mask      ndarray    6: 6 elems, type `bool`, 6 bytes
b           ndarray    21: 21 elems, type `float64`, 168 bytes
b_array     ndarray    3: 3 elems, type `int64`, 24 bytes
b_list      list       n=3
big_array   ndarray    33: 33 elems, type `float64`, 264 bytes
np          module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


In [80]:
a_mask

array([ True,  True,  True, False, False, False])

This MASK serves as useful purpose. It identifies all elements in array 'a' that satisfy conditional test!!Q
This means we can use the mask to keep o filter elements that meet out test

In [81]:
a[a_mask]

array([-101,    1,    2])

In [82]:
a_mask

array([ True,  True,  True, False, False, False])

I need to rememeber what object the MASK was applied to an what conditional test is

In [83]:
a_mask

array([ True,  True,  True, False, False, False])

In [84]:
a[a < 3]

array([-101,    1,    2])

In [85]:
b

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

Return all values that are less than 3

In [86]:
b [ b < 3 ]

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5])

### Combine multiple arrays together
lets first create 2 lists

In [87]:
a_list = [1,2,3]
b_list = [3,2,1]

In [88]:
a_list + b_list

[1, 2, 3, 3, 2, 1]

Plus operator doesn't work the same way with NumPy

In [89]:
a_array = np.array( a_list )

In [90]:
b_array = np.array( b_list )

In [91]:
a_array + b_array

array([4, 4, 4])

 But...sometimes we need to modify the OBJECTS rather than ADDING the values together
 We can combine or concatenate the arrays using np.concatenate() function

In [92]:
np.concatenate([ a_array, b_array])

array([1, 2, 3, 3, 2, 1])

In [93]:
[a_array, b_array]

[array([1, 2, 3]), array([3, 2, 1])]

In [94]:
np.concatenate([a_array, b_array, a, b])

array([   1. ,    2. ,    3. ,    3. ,    2. ,    1. , -101. ,    1. ,
          2. ,    3. ,    4. ,  101. ,   -5. ,   -4.5,   -4. ,   -3.5,
         -3. ,   -2.5,   -2. ,   -1.5,   -1. ,   -0.5,    0. ,    0.5,
          1. ,    1.5,    2. ,    2.5,    3. ,    3.5,    4. ,    4.5,
          5. ])

In [95]:
type(np.concatenate([a_array, b_array, a, b]))

numpy.ndarray

In [96]:
np.concatenate([a_array, b_array, a, b]).ndim

1

In [97]:
np.concatenate([a_array, b_array, a, b]).shape

(33,)

In [98]:
np.concatenate([a_array, b_array, a, b]).size

33

In [99]:
big_array = np.concatenate([a_array, a, b, b_array])

In [100]:
big_array.ndim

1

In [101]:
big_array.shape

(33,)

In [102]:
big_array.size

33

In [103]:
%whos

Variable    Type       Data/Info
--------------------------------
a           ndarray    6: 6 elems, type `int64`, 48 bytes
a_array     ndarray    3: 3 elems, type `int64`, 24 bytes
a_list      list       n=3
a_mask      ndarray    6: 6 elems, type `bool`, 6 bytes
b           ndarray    21: 21 elems, type `float64`, 168 bytes
b_array     ndarray    3: 3 elems, type `int64`, 24 bytes
b_list      list       n=3
big_array   ndarray    33: 33 elems, type `float64`, 264 bytes
np          module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


### Change element order by sorting
There are multiple ways, let's see sort()

In [104]:
big_array

array([   1. ,    2. ,    3. , -101. ,    1. ,    2. ,    3. ,    4. ,
        101. ,   -5. ,   -4.5,   -4. ,   -3.5,   -3. ,   -2.5,   -2. ,
         -1.5,   -1. ,   -0.5,    0. ,    0.5,    1. ,    1.5,    2. ,
          2.5,    3. ,    3.5,    4. ,    4.5,    5. ,    3. ,    2. ,
          1. ])

In [105]:
big_array.sort()

In [106]:
big_array

array([-101. ,   -5. ,   -4.5,   -4. ,   -3.5,   -3. ,   -2.5,   -2. ,
         -1.5,   -1. ,   -0.5,    0. ,    0.5,    1. ,    1. ,    1. ,
          1. ,    1.5,    2. ,    2. ,    2. ,    2. ,    2.5,    3. ,
          3. ,    3. ,    3. ,    3.5,    4. ,    4. ,    4.5,    5. ,
        101. ])

Descending order is not straight forward in .sort() from NumPy

### Summarize
summarizing values in an array returns fewer values
we have already seen several important functions, such as summing, mean, variance, SD
however we need to define functions to execute those tasks in base Python
NumPy is much easier to summarizing that Python but...we must be careful

In [107]:
big_array.sum()

22.0

In [108]:
big_array

array([-101. ,   -5. ,   -4.5,   -4. ,   -3.5,   -3. ,   -2.5,   -2. ,
         -1.5,   -1. ,   -0.5,    0. ,    0.5,    1. ,    1. ,    1. ,
          1. ,    1.5,    2. ,    2. ,    2. ,    2. ,    2.5,    3. ,
          3. ,    3. ,    3. ,    3.5,    4. ,    4. ,    4.5,    5. ,
        101. ])

In [109]:
%whos

Variable    Type       Data/Info
--------------------------------
a           ndarray    6: 6 elems, type `int64`, 48 bytes
a_array     ndarray    3: 3 elems, type `int64`, 24 bytes
a_list      list       n=3
a_mask      ndarray    6: 6 elems, type `bool`, 6 bytes
b           ndarray    21: 21 elems, type `float64`, 168 bytes
b_array     ndarray    3: 3 elems, type `int64`, 24 bytes
b_list      list       n=3
big_array   ndarray    33: 33 elems, type `float64`, 264 bytes
np          module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>


we can calculate MIN and max values in array

In [111]:
big_array.min()

-101.0

In [112]:
big_array.max()

101.0

The AVERAGE is calculate with the .mean() method!

In [113]:
big_array.mean()

0.6666666666666666

In [114]:
a

array([-101,    1,    2,    3,    4,  101])

In [115]:
a.mean()

1.6666666666666667

In [116]:
b.mean()

0.0

NumPy also has a method for the VARIANCE!!!


In [117]:
big_array.var()

625.3888888888889

In [118]:
a.var()

3402.555555555556

In [119]:
b.var()

9.166666666666666

 there is also method for standard deviation

In [121]:
big_array.std()

25.007776568277496

Standard Deviation is the sq root of variance

In [123]:
big_array.var() ** (1/2)

25.007776568277496

In [125]:
big_array.std() ** 2 

625.388888888889

BUT ..very important!!!
The above values are WRONG!!!!
NumPy is dangerous!!!
It's made by a company, used by millions of people in other companies
NumPy uses a wrong method to calculate these
ddof argument must be equal to 1 but it is 0 in NumPy

In [126]:
a[0]

-101

In [127]:
a[0].std()

0.0

In [128]:
a[0].std(ddof=1)

/opt/anaconda3/envs/cmpinf2100/lib/python3.8/site-packages/numpy/core/_methods.py:269: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/opt/anaconda3/envs/cmpinf2100/lib/python3.8/site-packages/numpy/core/_methods.py:261: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


nan

NEVER use the DEFAULT `.var()` or `.std()` arguments!!!!
ALWAYS set the ddof=1!!!!

In [129]:
big_array.var(ddof=1)

644.9322916666667

In [130]:
big_array.std(ddof=1)

25.395517156905207

Compare the BIased and unbiased estimators

In [133]:
'BIASED: %1.6f, UNBIASED:%1.6f' % (big_array.var(), big_array.var(ddof=1))

'BIASED: 625.388889, UNBIASED:644.932292'