## CMPINF 2100 Week 03
### Manipulating 2D arrays
We can manipulate 2D just like 1D but be carefule

In [1]:
import numpy as np

### Create arrays
we will use 1D array to contrast with manipulating 2D arrays

In [2]:
my_1d = np.arange(6)

In [3]:
my_1d 

array([0, 1, 2, 3, 4, 5])

In [6]:
my_2d = np.array([[0,0,0],
                [1,1,1],
                [2,2,2],
                [3,3,3]])

In [8]:
my_2d.ndim

2

In [9]:
my_2d.shape

(4, 3)

In [10]:
my_2d.size

12

In [11]:
my_1d.shape

(6,)

### Slicing

In [12]:
my_1d[0]

0

In [15]:
my_1d[-1]

5

In [16]:
my_1d[:3]

array([0, 1, 2])

In [17]:
my_1d[3:]

array([3, 4, 5])

what happens if we slice a 2D array just like 1D array

In [18]:
my_2d[0]

array([0, 0, 0])

In [19]:
my_2d[-1]

array([3, 3, 3])

In [20]:
my_2d

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

Providing a single index to SLICE causes NumPy to slice the ROWS!!!
It turns ALL columns from that row
the more formal syntax uses the : operator specify return ALL rows!!!

In [22]:
my_2d[0,:]

array([0, 0, 0])

slicing or indexing 2D arrays requires an index for rows and columns

In [23]:
my_2d

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [24]:
my_2d[0, 0]

0

In [25]:
my_2d[-1, -1]

3

In [27]:
 my_2d[:3,1]

array([0, 1, 2])

## Conditional subset
we can apply conditional subset for 2d

In [28]:
my_2d

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [29]:
my_2d[:,1]

array([0, 1, 2, 3])

In [30]:
my_2d[:, 1] > 1

array([False, False,  True,  True])

In [31]:
my_1d > 1

array([False, False,  True,  True,  True,  True])

In [32]:
my_2d[my_2d[:,1] > 1, :]

array([[2, 2, 2],
       [3, 3, 3]])

let's see this again but finding all ros with EVEN values in 1 column

In [33]:
6 % 2

0

In [34]:
7%2

1

In [35]:
my_2d[my_2d[:, 1] % 2 == 0, :]

array([[0, 0, 0],
       [2, 2, 2]])

Odd values

In [36]:
my_2d[my_2d[:, 1] % 2 != 0, :]

array([[1, 1, 1],
       [3, 3, 3]])

In [37]:
odd_array = my_2d[my_2d[:, 0] % 2 != 0, :2]

In [38]:
odd_array

array([[1, 1],
       [3, 3]])

Arrays are mutable...so we can change values!

In [39]:
odd_array[0,0] = 101

In [40]:
odd_array

array([[101,   1],
       [  3,   3]])

In [41]:
odd_array[-1,-1] = -101

In [42]:
odd_array

array([[ 101,    1],
       [   3, -101]])

But what if we SLICED rather than applied a MASK to conditionally subset larger array?

In [44]:
odd_b = my_2d[1:4:2, :2]

In [45]:
odd_b

array([[1, 1],
       [3, 3]])

In [46]:
%whos

Variable    Type       Data/Info
--------------------------------
my_1d       ndarray    6: 6 elems, type `int64`, 48 bytes
my_2d       ndarray    4x3: 12 elems, type `int64`, 96 bytes
np          module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
odd_array   ndarray    2x2: 4 elems, type `int64`, 32 bytes
odd_b       ndarray    2x2: 4 elems, type `int64`, 32 bytes


In [47]:
odd_b[0,0] = 301

In [48]:
odd_b[-1,-1] = -301

In [49]:
odd_b

array([[ 301,    1],
       [   3, -301]])

In [50]:
my_2d

array([[   0,    0,    0],
       [ 301,    1,    1],
       [   2,    2,    2],
       [   3, -301,    3]])

SLICING array into smaller objects can create a SIDE EFFECT!!!!
the sliced array POINTS back to the larger array it originally came from!!!!
Modifying the SLICED smaller array will therefore impact the original larger array it points to!!!
SLICING via masked or conditional subset may not produce the same side effect

We can REMOVE the POINTING SIDE EFFECT by forcing HARD OR DEEP COPIES!!!!

In [51]:
my_2d

array([[   0,    0,    0],
       [ 301,    1,    1],
       [   2,    2,    2],
       [   3, -301,    3]])

In [53]:
odd_copy = my_2d[ 1:4:2].copy()

In [54]:
odd_copy

array([[ 301,    1,    1],
       [   3, -301,    3]])

### Sort

When we sort we needd to rememeber it modifies in place and we should consider the DIMENSION or AXIS we are sorting over!!!

In [55]:
my_2d

array([[   0,    0,    0],
       [ 301,    1,    1],
       [   2,    2,    2],
       [   3, -301,    3]])

In [56]:
my_2d.sort(axis=0) # down the rows - top to bottom sorted

In [57]:
my_2d

array([[   0, -301,    0],
       [   2,    0,    1],
       [   3,    1,    2],
       [ 301,    2,    3]])

In [59]:
my_2d.sort(axis=1) # across the column - lef to right sorted

In [60]:
my_2d

array([[-301,    0,    0],
       [   0,    1,    2],
       [   1,    2,    3],
       [   2,    3,  301]])

### Summarize
1D summaries

In [61]:
my_1d

array([0, 1, 2, 3, 4, 5])

In [62]:
my_1d.min()

0

In [63]:
my_1d.max()

5

In [65]:
my_1d.mean()

2.5

What happens when we summarize 2d array

In [66]:
my_2d.min()

-301

retruns it from the entire array - we not want over all
summarize down the columns and rows

In [67]:
my_2d.mean(axis=0)

array([-74.5,   1.5,  76.5])

In [68]:
my_2d.std(ddof=1, axis=0)

array([151.00220749,   1.29099445, 149.67186331])

In [69]:
my_2d.std(ddof=1, axis=1)

array([173.78243103,   1.        ,   1.        , 172.33978067])

---

## 🧠 **Brief Explanation**

### 🔹 1. What happens when you “slice” an array

When you do something like:

```python
import numpy as np

big = np.array([10, 20, 30, 40, 50])
small = big[1:4]   # slice
```

➡️ The new array `small` is **not a copy** — it’s a **view** (a *window* into the original array).

That means:

* Both `small` and `big` share the **same data in memory**.
* If you modify one, the other changes too.

---

### 🔹 2. The “Side Effect”

Since both variables point to the same data, any change to one **affects the other**:

```python
small[0] = 999
print(big)   # → [10, 999, 30, 40, 50]
```

👉 This is the **side effect** — an **unintended change** to the original array.

---

### 🔹 3. Why it happens

NumPy slicing returns a **view** for performance reasons:

* It avoids making unnecessary copies of large datasets.
* But that means you must be careful when modifying slices.

---

### 🔹 4. When the side effect **does not** happen

If you use:

* **Masked slicing** (like `big[big > 20]`)
* Or use `.copy()` explicitly

You get a **new independent array**, so changes won’t affect the original.

Example:

```python
subset = big[big > 20]     # conditional subset
subset[0] = 999
print(big)   # big stays unchanged
```

---

## ✅ **What to Do / What Not to Do**

| **Action**                     | **What It Does**                     | ✅ / ❌          | **Reason / Note**                    |
| ------------------------------ | ------------------------------------ | -------------- | ------------------------------------ |
| `small = big[2:5]`             | Creates a **view** (linked to `big`) | ⚠️ Be cautious | Changes in `small` affect `big`      |
| `small = big[2:5].copy()`      | Creates a **true copy**              | ✅ Safe         | Independent object                   |
| `small[0] = 999`               | Modifies shared data                 | ❌ Dangerous    | Causes side effect                   |
| `subset = big[big > 20]`       | Creates new array (not view)         | ✅ Safe         | Conditional slicing makes copy       |
| `np.copy(big)`                 | Makes a full deep copy               | ✅ Safe         | No side effects                      |
| Use slicing for reading only   | Safe                                 | ✅              | Side effects occur only when writing |
| Modify slice without `.copy()` | Risky                                | ❌              | Might alter original unintentionally |

---

### ⚡ **Golden Rule**

> 🧩 *If you intend to modify the sliced data, always use `.copy()`.*

```python
small = big[1:4].copy()
small[0] = 999
print(big)   # original remains unchanged
```

---

### 🧭 **Quick Summary**

| Concept                           | Behavior                         |
| --------------------------------- | -------------------------------- |
| Normal slicing (`a[1:4]`)         | Returns a *view* (shares memory) |
| Conditional slicing (`a[a > 10]`) | Returns a *copy*                 |
| `.copy()`                         | Creates an independent array     |
| Modifying view                    | Affects original                 |
| Modifying copy                    | Does not affect original         |

---

## 🧩 **Case 1 — Normal Slice (View → Side Effect!)**

```
Memory layout:

 big array
 ┌────────────────────────────────────┐
 │ 10 │ 20 │ 30 │ 40 │ 50 │ 60 │ 70 │
 └────────────────────────────────────┘
   ↑      ↑      ↑
   │      │
   │   slice points to this portion (indexes 1–3)
   │
 small = big[1:4]
 ┌────────────────────┐
 │ 20 │ 30 │ 40 │  ←───┘ (points to same memory)
 └────────────────────┘

# Modify slice
 small[0] = 999

Result:
 ┌────────────────────────────────────┐
 │ 10 │ 999 │ 30 │ 40 │ 50 │ 60 │ 70 │  ← big changed!
 └────────────────────────────────────┘
```

✅ Efficient
⚠️ But **any change in `small` affects `big`** — this is the **side effect**.

---

## 🧩 **Case 2 — Slice + Copy (Independent Copy → No Side Effect)**

```
 big array
 ┌────────────────────────────────────┐
 │ 10 │ 20 │ 30 │ 40 │ 50 │ 60 │ 70 │
 └────────────────────────────────────┘

 small = big[1:4].copy()
 ┌────────────────────┐
 │ 20 │ 30 │ 40 │     │   (stored in new memory)
 └────────────────────┘

# Modify slice
 small[0] = 999

Result:
 big remains unchanged!
 ┌────────────────────────────────────┐
 │ 10 │ 20 │ 30 │ 40 │ 50 │ 60 │ 70 │
 └────────────────────────────────────┘

 small
 ┌────────────────────┐
 │ 999 │ 30 │ 40 │    │  ← safe, no side effect
 └────────────────────┘
```

✅ Safe for modifications
❌ Slightly more memory used (because of copy)

---

## 🧩 **Case 3 — Masked / Conditional Slice (Automatic Copy)**

```
 big = [10, 20, 30, 40, 50]
 small = big[big > 30]

 big
 ┌──────────────────────────┐
 │ 10 │ 20 │ 30 │ 40 │ 50 │
 └──────────────────────────┘

 small
 ┌──────────────┐
 │ 40 │ 50 │     │  (new independent array)
 └──────────────┘

 small[0] = 999   # does NOT affect big
```

✅ Safe, because conditional slicing makes a new array automatically.

---

### 💡 **Summary**

| Type of Slice                    | Shares Memory? | Safe to Modify? |
| -------------------------------- | -------------- | --------------- |
| Regular slice (`a[1:4]`)         | ✅ Yes          | ❌ No            |
| Slice + `.copy()`                | ❌ No           | ✅ Yes           |
| Conditional slice (`a[a>value]`) | ❌ No           | ✅ Yes           |

---