## CPINF 2100 Week 04
### Introduction to Pandas DataFrame
The previous video was all about Pandas Series. A sereies contains values associated with a single variable
The dataframe is a collection of variables or collection of Panda Series

In [1]:
import numpy as np
import pandas as pd

## NumPy to DataFrames
Panda's DataFrame is kind of like a 2D NumPy array
So let's create a DataFrame from a 2D NumPy array

In [2]:
x = np.arange(1, 25).reshape(6, -1)

In [3]:
x.shape

(6, 4)

In [4]:
x.ndim

2

In [5]:
x.size

24

In [6]:
x [0]

array([1, 2, 3, 4])

In [7]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [9]:
x[:,0] # first column

array([ 1,  5,  9, 13, 17, 21])

In [10]:
x[:, -1] # last column

array([ 4,  8, 12, 16, 20, 24])

In [13]:
x[0, -1] # first row last item

4

In [15]:
x[-1, 0] # last row first item

21

In [18]:
x[:3, :2] # firt 3 rows and first 2 columns

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [19]:
xdf = pd.DataFrame( x)

In [20]:
%whos

Variable   Type         Data/Info
---------------------------------
np         module       <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
pd         module       <module 'pandas' from '/o<...>ages/pandas/__init__.py'>
x          ndarray      6x4: 24 elems, type `int64`, 192 bytes
xdf        DataFrame        0   1   2   3\n0   1 <...>19  20\n5  21  22  23  24


In [21]:
type( xdf )

pandas.core.frame.DataFrame

In [22]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [23]:
print(xdf)

    0   1   2   3
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24


In [25]:
xdf # don't print just display - it's easier to read

,0,1,2,3
0,1,2,3,4
1,5,6,7,8
2,9,10,11,12
3,13,14,15,16
4,17,18,19,20
5,21,22,23,24


Provide a single index to slice the NumPy 2D array

In [26]:
x[0]

array([1, 2, 3, 4])

what happens if we do it for df

In [28]:
xdf[0]

0     1
1     5
2     9
3    13
4    17
5    21
Name: 0, dtype: int64

In [29]:
xdf[:, 0]

KeyError: (slice(None, None, None), 0)

DF has other ways to do so

### Dictionary to DF

In [30]:
# MULTI ENTRY VALUE

In [31]:
baseball_dict = {'City': ['Pittsburgh', 'Cincinnati', 'Chicago', 'St. Louis', 'Milwaukee'],
                'Team': ['Pirates', 'Reds', 'Cubs', 'Cardinals', 'Brewers'],
                 'Division': 5 * ['Central'],
                 'League': 5 * ['NL']}

In [32]:
baseball_dict

{'City': ['Pittsburgh', 'Cincinnati', 'Chicago', 'St. Louis', 'Milwaukee'],
 'Team': ['Pirates', 'Reds', 'Cubs', 'Cardinals', 'Brewers'],
 'Division': ['Central', 'Central', 'Central', 'Central', 'Central'],
 'League': ['NL', 'NL', 'NL', 'NL', 'NL']}

In [33]:
baseball_dict['City']

['Pittsburgh', 'Cincinnati', 'Chicago', 'St. Louis', 'Milwaukee']

In [34]:
baseball_dict['Team']

['Pirates', 'Reds', 'Cubs', 'Cardinals', 'Brewers']

### convert to DF

In [35]:
baseball_df = pd.DataFrame( baseball_dict )

In [36]:
baseball_df

,City,Team,Division,League
0,Pittsburgh,Pirates,Central,NL
1,Cincinnati,Reds,Central,NL
2,Chicago,Cubs,Central,NL
3,St. Louis,Cardinals,Central,NL
4,Milwaukee,Brewers,Central,NL


## Dictionary key become column name

In [37]:
baseball_df.columns

Index(['City', 'Team', 'Division', 'League'], dtype='object')

In [38]:
baseball_df.index

RangeIndex(start=0, stop=5, step=1)

In [40]:
xdf.dtypes

0    int64
1    int64
2    int64
3    int64
dtype: object

In [42]:
baseball_df.dtypes # pandas call strings - objects

City        object
Team        object
Division    object
League      object
dtype: object

### DF methods

In [45]:
xdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       6 non-null      int64
 1   1       6 non-null      int64
 2   2       6 non-null      int64
 3   3       6 non-null      int64
dtypes: int64(4)
memory usage: 320.0 bytes


In [46]:
baseball_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   City      5 non-null      object
 1   Team      5 non-null      object
 2   Division  5 non-null      object
 3   League    5 non-null      object
dtypes: object(4)
memory usage: 288.0+ bytes


In [47]:
baseball_df.describe()

,City,Team,Division,League
count,5,5,5,5
unique,5,5,1,1
top,Pittsburgh,Pirates,Central,NL
freq,1,1,5,5


In [48]:
xdf.describe()

,0,1,2,3
count,6.000000,6.000000,6.000000,6.000000
mean,11.000000,12.000000,13.000000,14.000000
std,7.483315,7.483315,7.483315,7.483315
min,1.000000,2.000000,3.000000,4.000000
25%,6.000000,7.000000,8.000000,9.000000
50%,11.000000,12.000000,13.000000,14.000000
75%,16.000000,17.000000,18.000000,19.000000
max,21.000000,22.000000,23.000000,24.000000


In [51]:
x.mean(axis=0)

array([11., 12., 13., 14.])

In [52]:
x.std(axis=0, ddof=1)

array([7.48331477, 7.48331477, 7.48331477, 7.48331477])

In [53]:
baseball_df.describe()

,City,Team,Division,League
count,5,5,5,5
unique,5,5,1,1
top,Pittsburgh,Pirates,Central,NL
freq,1,1,5,5


### how to sort

In [54]:
baseball_df.sort_values(['Team'])

,City,Team,Division,League
4,Milwaukee,Brewers,Central,NL
3,St. Louis,Cardinals,Central,NL
2,Chicago,Cubs,Central,NL
0,Pittsburgh,Pirates,Central,NL
1,Cincinnati,Reds,Central,NL


#index retain original '.index' attribute positions)
want to ignore the index

In [55]:
baseball_df.sort_values(['Team'], ignore_index=True )

,City,Team,Division,League
0,Milwaukee,Brewers,Central,NL
1,St. Louis,Cardinals,Central,NL
2,Chicago,Cubs,Central,NL
3,Pittsburgh,Pirates,Central,NL
4,Cincinnati,Reds,Central,NL


In [57]:
baseball_df.sort_values(['Team'], ignore_index=True, ascending=False)

,City,Team,Division,League
0,Cincinnati,Reds,Central,NL
1,Pittsburgh,Pirates,Central,NL
2,Chicago,Cubs,Central,NL
3,St. Louis,Cardinals,Central,NL
4,Milwaukee,Brewers,Central,NL


to store it, assign result to new object but force the deep copy

In [58]:
baseball_df_b = baseball_df.sort_values(['Team'], ignore_index=True, ascending=False).copy()

In [59]:
baseball_df_b

,City,Team,Division,League
0,Cincinnati,Reds,Central,NL
1,Pittsburgh,Pirates,Central,NL
2,Chicago,Cubs,Central,NL
3,St. Louis,Cardinals,Central,NL
4,Milwaukee,Brewers,Central,NL


We can also force PANDAS to modify in place using the inplace arguement

In [60]:
baseball_df.sort_values(['Team'], inplace=True)

In [61]:
baseball_df

,City,Team,Division,League
4,Milwaukee,Brewers,Central,NL
3,St. Louis,Cardinals,Central,NL
2,Chicago,Cubs,Central,NL
0,Pittsburgh,Pirates,Central,NL
1,Cincinnati,Reds,Central,NL


## Summary
* DF from NumPy and Dictinaries
* Highligted DF are 2D objects - have 2 dimentions - rows and columns
* This was to highlight that the KEY becomes the COLUMN NAME
* Think Pandas DF as combination of the NumPy 2D array and the PYthon Dictionary!!! 